name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/deployments" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"app_id": "faf03500-1eb5-4b10-9d08-c8446bdeb935"}'
